name: dictionary_app # Replace with your project name if different
description: A Dart console app that fetches word definitions.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0' # Or your Dart SDK version

dependencies:
  http: ^1.2.1 # Or the latest version from pub.dev

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0